name: sudoku
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.3
  dio: ^5.5.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.3
  go_router: ^14.2.0
  haptic_feedback: ^0.5.1+1
  hooks_riverpod: ^2.5.1
  i18n_extension: ^12.0.1
  json_annotation: ^4.9.0
  lm_labs_utils: ^1.1.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  sudoku_dart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.4
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  lm_labs_flutter_lints: ^0.1.0
  lm_labs_generator: ^0.0.1
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/flutter_logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/flutter_logo.png
  info_plist_files:
    - "ios/Runner/Info.plist"
